### ISSUE TITLE
tuple index out of range

### ISSUE THREAD

**Issue by ingalls** [developmentseed/raster-uploader#14]
### Context

A user submitted NetCDF:
```
LIS_HIST_202010010000.d01.nc
```

Throws the following error

```
tuple index out of range
```

```


OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
--
START RequestId: 07db4f5a-49c0-53df-987b-1464cdf807fe Version: $LATEST
OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
NetCDF Conversion
{'upload': 54, 'type': 'selection', 'config': {'upload': 54, 'cog': {'overview': '5', 'blocksize': '512', 'compression': 'deflate'}}, 'step': {'title': 'Select a NetCDF Variable', 'selections': [{'name': 'lat'}, {'name': 'lon'}, {'name': 'time'}, {'name': 'Evap_tavg'}, {'name': 'Qs_tavg'}, {'name': 'Qsb_tavg'}, {'name': 'AvgSurfT_tavg'}, {'name': 'SWE_tavg'}, {'name': 'SnowDepth_tavg'}, {'name': 'SoilMoist_tavg'}, {'name': 'TWS_tavg'}, {'name': 'GWS_tavg'}, {'name': 'GPP_tavg'}, {'name': 'NEE_tavg'}, {'name': 'LAI_tavg'}], 'variable': 'variable'}}
END RequestId: 07db4f5a-49c0-53df-987b-1464cdf807fe
REPORT RequestId: 07db4f5a-49c0-53df-987b-1464cdf807fe	Duration: 13620.20 ms	Billed Duration: 13621 ms	Memory Size: 1024 MB	Max Memory Used: 186 MB
START RequestId: b4eea184-eb89-502f-afb9-faba6f22f851 Version: $LATEST
NetCDF Conversion
ERROR tuple index out of range
Traceback (most recent call last):
File "/var/task/handler.py", line 107, in handler
pth = nc(filtered[0], event)
File "/var/task/lib/nc.py", line 75, in nc
src_height, src_width = variable.shape[0], variable.shape[1]
IndexError: tuple index out of range
{'upload': 54, 'type': 'error', 'config': {'cog': {'overview': '5', 'blocksize': '512', 'compression': 'deflate'}, 'upload': 54, 'variable': 'AvgSurfT_tavg'}, 'step': {'message': 'tuple index out of range'}}
END RequestId: b4eea184-eb89-502f-afb9-faba6f22f851
REPORT RequestId: b4eea184-eb89-502f-afb9-faba6f22f851	Duration: 1224.58 ms	Billed Duration: 1225 ms	Memory Size: 1024 MB	Max Memory Used: 256 MB


```

Ref: https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/issues/151

**Comment by ingalls** [comment]
Fixed: https://github.com/developmentseed/raster-uploader/pull/13
